import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart,Plus,X,Home,CalendarDays,ScanLine,UserRound,MessageCircle,ShoppingBasket,ArrowLeft,Share2} from 'lucide-react';
import './index.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const basePrefs={diet:'Vegetarian',cuisine:'',calorie_limit:600,allergies:[],goal:'Maintenance'};
function App(){
 const [screen,setScreen]=useState('home'),[ingredients,setIngredients]=useState(['onion','tomato','spinach']),[input,setInput]=useState(''),[prefs,setPrefs]=useState(basePrefs),[recipes,setRecipes]=useState([]),[selected,setSelected]=useState(null),[subs,setSubs]=useState(null),[plan,setPlan]=useState(null),[grocery,setGrocery]=useState(null),[chat,setChat]=useState([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [favorites,setFavorites]=useState(()=>JSON.parse(localStorage.getItem('favorites')||'[]'));
 useEffect(()=>localStorage.setItem('favorites',JSON.stringify(favorites)),[favorites]);
 const add=()=>{const x=input.trim().toLowerCase();if(x&&!ingredients.includes(x))setIngredients([...ingredients,x]);setInput('')};
 const call=async(path,opts={})=>{setLoading(true);setError('');try{const r=await fetch(API+path,opts);const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={detail:text||'Request failed'}}if(!r.ok)throw new Error(d.detail||'Request failed');return d}catch(e){const message=e instanceof TypeError?'Cannot reach the recipe service. Start FastAPI on port 8000.':e.message||'Request failed';setError(message);throw e}finally{setLoading(false)}};
 const fetchRecipes=async()=>{try{const d=await call('/recipes/suggest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredients,...prefs})});setRecipes(d.recipes||[]);setScreen('recipes')}catch{}};
 const openRecipe=async id=>{try{const d=await call('/recipes/'+id);const fromList=recipes.find(x=>x.id===id);setSelected({...d,missing_ingredients:fromList?.missing_ingredients||[]});setScreen('detail')}catch{}};
 const getSubs=async()=>{try{const d=await call('/substitutions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({missing_ingredients:selected?.missing_ingredients||[],diet:prefs.diet,allergies:prefs.allergies})});setSubs(d);setScreen('subs')}catch{}};
 const genPlan=async()=>{try{const d=await call('/meal-plan/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredients,...prefs})});setPlan(d);setScreen('plan')}catch{}};
 const genGrocery=async()=>{try{const d=await call('/grocery-list',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ingredients,...prefs})});setGrocery(d);setScreen('grocery')}catch{}};
 const sendChat=async()=>{if(!message.trim()||loading)return;const q=message.trim();setChat(c=>[...c,{role:'user',text:q}]);setMessage('');try{const d=await call('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q})});setChat(c=>[...c,{role:'assistant',text:d.answer}])}catch{}};
 const toggleFav=id=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);
 return <div className="min-h-screen bg-[#f7fbf8] pb-24"><header className="bg-white border-b sticky top-0 z-10"><div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between"><button onClick={()=>setScreen('home')} className="text-left"><b className="text-xl text-[#2E9E5B]">🥗 RecipeMind</b><p className="text-xs text-slate-500">Your Ingredients, Our Intelligence, Better Meals!</p></button><div className="flex gap-1"><button onClick={genGrocery} title="Grocery list" className="p-2 text-[#2E9E5B]"><ShoppingBasket/></button><button onClick={genPlan} title="Meal plan" className="p-2 text-[#2E9E5B]"><CalendarDays/></button></div></div></header>
 <main className="max-w-6xl mx-auto px-4 py-6">{loading&&<div role="status" className="mb-4 rounded-2xl bg-green-50 text-green-800 px-4 py-3">Working on it…</div>}{error&&<div role="alert" className="mb-4 rounded-2xl bg-red-50 text-red-700 px-4 py-3 flex justify-between gap-3">{error}<button onClick={()=>setError('')} aria-label="dismiss error"><X size={18}/></button></div>}
 {screen==='home'&&<HomeScreen ingredients={ingredients} input={input} setInput={setInput} add={add} remove={x=>setIngredients(ingredients.filter(i=>i!==x))} suggest={()=>setScreen('prefs')}/>} 
 {screen==='prefs'&&<PrefsScreen prefs={prefs} setPrefs={setPrefs} submit={fetchRecipes} back={()=>setScreen('home')}/>} 
 {screen==='recipes'&&<RecipeList recipes={recipes} open={openRecipe} favorites={favorites} toggleFav={toggleFav}/>} 
 {screen==='detail'&&selected&&<Detail recipe={selected} onBack={()=>setScreen('recipes')} onSubs={getSubs} favorite={favorites.includes(selected.id)} toggleFav={()=>toggleFav(selected.id)}/>} 
 {screen==='subs'&&subs&&<Subs data={subs} back={()=>setScreen('detail')}/>} 
 {screen==='plan'&&plan&&<Plan data={plan} back={()=>setScreen('home')}/>} 
 {screen==='grocery'&&grocery&&<Grocery data={grocery} back={()=>setScreen('home')}/>} 
 {screen==='chat'&&<Chat chat={chat} message={message} setMessage={setMessage} send={sendChat} loading={loading}/>} 
 {screen==='profile'&&<Profile favorites={favorites} recipes={recipes} open={openRecipe} toggleFav={toggleFav} chat={()=>setScreen('chat')} grocery={genGrocery}/>} 
 </main><nav className="fixed bottom-0 inset-x-0 bg-white border-t z-20"><div className="max-w-6xl mx-auto grid grid-cols-4 py-2 text-xs"><Nav i={<Home/>} t="Home" a={()=>setScreen('home')}/><Nav i={<CalendarDays/>} t="Plan" a={genPlan}/><Nav i={<ScanLine/>} t="Scan" a={()=>setError('Fridge image scanning is an optional prototype feature and is not implemented yet.')}/><Nav i={<UserRound/>} t="Profile" a={()=>setScreen('profile')}/></div></nav></div>}
function Nav({i,t,a}){return <button onClick={a} className="flex flex-col items-center gap-1 text-slate-500 hover:text-[#2E9E5B]">{i}{t}</button>}
function HomeScreen({ingredients,input,setInput,add,remove,suggest}){return <section><div className="py-6"><span className="inline-flex rounded-full bg-green-100 text-green-800 px-3 py-1 text-sm">AI recipe + nutrition assistant</span><h1 className="text-4xl md:text-5xl font-bold mt-4">What’s in your fridge?</h1><p className="text-slate-500 mt-3 max-w-xl">Tell us what you have and we’ll build calorie-aware meals around it.</p></div><div className="bg-white rounded-3xl p-4 md:p-6 shadow-soft"><div className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add an ingredient..." aria-label="ingredient" className="flex-1 border rounded-2xl px-4 py-3"/><button onClick={add} aria-label="add ingredient" className="bg-[#2E9E5B] text-white rounded-2xl px-4"><Plus/></button></div><div className="flex flex-wrap gap-2 mt-4">{ingredients.map(x=><span className="px-3 py-2 bg-green-50 text-green-800 rounded-full text-sm flex gap-2 items-center" key={x}>{x}<button onClick={()=>remove(x)} aria-label={`remove ${x}`}><X size={14}/></button></span>)}</div><button disabled={!ingredients.length} onClick={suggest} className="w-full mt-5 bg-[#2E9E5B] disabled:bg-slate-300 text-white rounded-2xl py-3 font-semibold">Find Recipes</button></div></section>}
function PrefsScreen({prefs,setPrefs,submit,back}){const update=(k,v)=>setPrefs({...prefs,[k]:v});return <section><button onClick={back} className="text-slate-500 flex gap-1 items-center"><ArrowLeft size={16}/> Back</button><h2 className="text-3xl font-bold mt-4">Personalize your meals</h2><div className="grid md:grid-cols-2 gap-4 mt-5">{[['diet',['Vegetarian','Vegan','Non-Veg']],['goal',['Weight loss','Muscle gain','Maintenance']]].map(([k,opts])=><div className="bg-white rounded-3xl p-4 shadow-soft" key={k}><h3 className="font-semibold capitalize">{k}</h3><div className="flex flex-wrap gap-2 mt-3">{opts.map(o=><button key={o} onClick={()=>update(k,o)} className={`px-3 py-2 rounded-full ${prefs[k]===o?'bg-[#2E9E5B] text-white':'bg-slate-100'}`}>{o}</button>)}</div></div>)}<div className="bg-white rounded-3xl p-4 shadow-soft"><h3 className="font-semibold">Cuisine</h3><select value={prefs.cuisine} onChange={e=>update('cuisine',e.target.value)} className="mt-3 w-full border rounded-xl p-3"><option value="">Any cuisine</option><option>Indian</option><option>Italian</option><option>Mexican</option><option>Mediterranean</option></select></div><div className="bg-white rounded-3xl p-4 shadow-soft"><h3 className="font-semibold">Calorie limit per meal</h3><select value={prefs.calorie_limit} onChange={e=>update('calorie_limit',Number(e.target.value))} className="mt-3 w-full border rounded-xl p-3"><option value="400">400 kcal</option><option value="600">600 kcal</option><option value="800">800 kcal</option></select></div><div className="bg-white rounded-3xl p-4 shadow-soft md:col-span-2"><h3 className="font-semibold">Allergies</h3><div className="flex flex-wrap gap-2 mt-3">{['Nuts','Dairy','Gluten'].map(a=><button key={a} onClick={()=>update('allergies',prefs.allergies.includes(a)?prefs.allergies.filter(x=>x!==a):[...prefs.allergies,a])} className={`px-4 py-2 rounded-full ${prefs.allergies.includes(a)?'bg-orange-500 text-white':'bg-slate-100'}`}>{a}</button>)}</div></div></div><button onClick={submit} className="mt-5 w-full bg-[#2E9E5B] text-white rounded-2xl py-3 font-semibold">Show personalized recipes</button></section>}
function RecipeList({recipes,open,favorites,toggleFav}){const [f,setF]=useState('All');const shown=recipes.filter(r=>f==='All'||(f==='<400 Cal'?r.calories<400:r.protein>=20));return <section><div className="flex flex-col md:flex-row md:justify-between gap-3 md:items-center"><h2 className="text-3xl font-bold">Recipes for you</h2><div className="flex gap-2 flex-wrap">{['All','<400 Cal','High Protein'].map(x=><button onClick={()=>setF(x)} key={x} className={`px-3 py-2 rounded-full text-sm ${f===x?'bg-[#2E9E5B] text-white':'bg-white'}`}>{x}</button>)}</div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-5">{shown.map(r=><article key={r.id} className="bg-white rounded-3xl overflow-hidden shadow-soft"><button onClick={()=>open(r.id)} className="w-full text-left"><img src={r.image} alt={r.name} loading="lazy" className="w-full h-48 object-cover"/><div className="p-4"><h3 className="font-bold">{r.name}</h3><p className="text-sm text-slate-500 mt-2">{r.calories} kcal · {r.protein}g protein · {r.time} min</p><p className="text-xs mt-2">{r.difficulty}</p><p className="text-xs text-[#2E9E5B] mt-2">{r.why_match||'Personalized match'}</p></div></button><div className="px-4 pb-4"><button onClick={()=>toggleFav(r.id)} aria-label="favorite" className="p-2 rounded-full bg-slate-50"><Heart size={18} fill={favorites.includes(r.id)?'currentColor':'none'} className={favorites.includes(r.id)?'text-orange-500':'text-slate-500'}/></button></div></article>)}</div>{!shown.length&&<div className="text-center py-16 text-slate-500 bg-white rounded-3xl mt-5">No recipes match these filters. Try a different preference or calorie limit.</div>}</section>}
function Detail({recipe,onBack,onSubs,favorite,toggleFav}){const share=()=>{const text=`${recipe.name} — ${recipe.calories} kcal, ${recipe.protein}g protein`;if(navigator.share)navigator.share({title:recipe.name,text}).catch(()=>{});else navigator.clipboard?.writeText(text)};return <section><button onClick={onBack} className="text-slate-500 flex gap-1 items-center"><ArrowLeft size={16}/> Recipes</button><img src={recipe.image} alt={recipe.name} className="w-full max-h-80 object-cover rounded-3xl mt-4"/><div className="flex justify-between items-start mt-5 gap-3"><h2 className="text-3xl font-bold">{recipe.name}</h2><div className="flex gap-2"><button onClick={toggleFav} aria-label="favorite recipe" className="p-2 rounded-full bg-white shadow-soft"><Heart fill={favorite?'currentColor':'none'} className={favorite?'text-orange-500':''}/></button><button onClick={share} aria-label="share recipe" className="p-2 rounded-full bg-white shadow-soft"><Share2 size={18}/></button></div></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-4">{[['Calories',recipe.calories+' kcal'],['Protein',recipe.protein+' g'],['Carbs',recipe.carbs+' g'],['Fat',recipe.fat+' g']].map(([a,b])=><div className="bg-white rounded-2xl p-3 text-center shadow-soft" key={a}><b>{b}</b><small className="block text-slate-500">{a}</small></div>)}</div><div className="bg-white rounded-3xl p-5 mt-5"><h3 className="font-bold">Ingredients</h3><ul className="list-disc pl-5 mt-2">{recipe.ingredients.map(x=><li key={x}>{x}</li>)}</ul><h3 className="font-bold mt-5">Instructions</h3><ol className="list-decimal pl-5 mt-2 space-y-2">{recipe.instructions.map(x=><li key={x}>{x}</li>)}</ol>{recipe.missing_ingredients?.length>0&&<><h3 className="font-bold mt-5">Missing ingredients</h3><p>{recipe.missing_ingredients.join(', ')}</p><div className="flex flex-wrap gap-2 mt-4"><button onClick={onSubs} className="bg-orange-500 text-white px-4 py-3 rounded-xl">Find substitutions</button></div></>}</div></section>}
function Subs({data,back}){return <section><button onClick={back} className="text-slate-500 flex gap-1 items-center"><ArrowLeft size={16}/> Recipe</button><h2 className="text-3xl font-bold mt-4">Smart substitutions</h2><div className="space-y-3 mt-5">{data.substitutions.map(s=><div className="bg-white rounded-3xl p-5 shadow-soft" key={s.ingredient}><b>{s.ingredient}</b><p className="text-slate-500 mt-1">{s.alternatives.length?s.alternatives.join(' · '):'No safe substitution found in the prototype dataset.'}</p><p className="text-sm mt-2">{s.explanation}</p></div>)}</div></section>}
function Plan({data,back}){const [mode,setMode]=useState('week');if(!data.days?.length)return <section><h2 className="text-3xl font-bold">No meal plan</h2><p className="mt-3 text-slate-500">{data.message}</p></section>;return <section><button onClick={back} className="text-slate-500 flex gap-1 items-center"><ArrowLeft size={16}/> Home</button><div className="flex flex-col sm:flex-row sm:justify-between gap-3 mt-4"><h2 className="text-3xl font-bold">Weekly meal plan</h2><div className="flex bg-white rounded-xl p-1">{['day','week'].map(x=><button key={x} onClick={()=>setMode(x)} className={`px-3 py-2 rounded-lg capitalize ${mode===x?'bg-[#2E9E5B] text-white':''}`}>{x}</button>)}</div></div><p className="text-sm text-slate-500 mt-2">Target: about {data.target_calories} kcal/day based on your selected meal limit.</p><div className="space-y-3 mt-5">{(mode==='day'?[data.days[0]]:data.days).map(d=><div className="bg-white rounded-3xl p-5 shadow-soft" key={d.day}><div className="flex justify-between"><b>{d.day}</b><span>{d.total_calories} kcal</span></div>{d.meals.map(m=><div className="flex justify-between gap-4 mt-3 text-sm" key={m.type}><span>{m.type}: {m.name}</span><span>{m.calories} kcal</span></div>)}</div>)}</div></section>}
function Grocery({data,back}){return <section><button onClick={back} className="text-slate-500 flex gap-1 items-center"><ArrowLeft size={16}/> Home</button><h2 className="text-3xl font-bold mt-4">Smart grocery list</h2><div className="bg-white rounded-3xl p-5 mt-5 shadow-soft">{data.items.length?data.items.map(x=><div className="flex justify-between border-b last:border-0 py-3 gap-4" key={x.ingredient}><span>{x.ingredient}</span><span className="text-slate-500">used by {x.recipe_count} recipe(s)</span></div>):<p className="text-slate-500">Nothing extra is needed for the current suggestions.</p>}</div></section>}
function Chat({chat,message,setMessage,send,loading}){return <section><h2 className="text-3xl font-bold">Cooking & nutrition chat</h2><div className="bg-white rounded-3xl p-4 mt-5 shadow-soft min-h-80">{!chat.length&&<p className="text-slate-500">Ask about cooking, nutrition, ingredients, or substitutions.</p>}{chat.map((m,i)=><div key={i} className={`mb-3 ${m.role==='user'?'text-right':''}`}><span className={`inline-block rounded-2xl px-4 py-3 max-w-[85%] ${m.role==='user'?'bg-[#2E9E5B] text-white':'bg-slate-100'}`}>{m.text}</span></div>)}<div className="flex gap-2 mt-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask a question..." aria-label="chat message" className="flex-1 border rounded-2xl px-4 py-3"/><button disabled={loading} onClick={send} className="bg-[#2E9E5B] disabled:bg-slate-300 text-white rounded-2xl px-5">Send</button></div></div></section>}
function Profile({favorites,recipes,open,toggleFav,chat,grocery}){const fav=recipes.filter(r=>favorites.includes(r.id));return <section><h2 className="text-3xl font-bold">Profile</h2><p className="text-slate-500 mt-2">Saved recipes and useful tools.</p><div className="grid md:grid-cols-3 gap-4 mt-5"><button onClick={chat} className="bg-white rounded-3xl p-5 shadow-soft text-left"><MessageCircle className="text-[#2E9E5B]"/><b className="block mt-3">Nutrition chat</b><span className="text-sm text-slate-500">Ask cooking and nutrition questions.</span></button><button onClick={grocery} className="bg-white rounded-3xl p-5 shadow-soft text-left"><ShoppingBasket className="text-[#2E9E5B]"/><b className="block mt-3">Grocery list</b><span className="text-sm text-slate-500">Build a list from your current matches.</span></button><div className="bg-white rounded-3xl p-5 shadow-soft"><Heart className="text-orange-500"/><b className="block mt-3">Favorites</b><span className="text-sm text-slate-500">{favorites.length} saved recipe(s)</span></div></div><h3 className="font-bold text-xl mt-8">Saved recipes</h3>{!fav.length?<div className="bg-white rounded-3xl p-8 mt-4 text-slate-500">Tap the heart on a recipe to save it here.</div>:<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">{fav.map(r=><div key={r.id} className="bg-white rounded-3xl p-4 shadow-soft"><button className="font-semibold text-left" onClick={()=>open(r.id)}>{r.name}</button><button onClick={()=>toggleFav(r.id)} className="float-right text-orange-500" aria-label="remove favorite"><Heart fill="currentColor" size={18}/></button></div>)}</div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
